version: '3.8'
services:
  nestjs-app_prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql:8.3 
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root  
      - MYSQL_DATABASE=nadinbase
      - MYSQL_USER=hesam
      - MYSQL_PASSWORD=root
      - MYSQL_TCP_PORT=3306