version: '3.8'
services:
  nestjs-app:
    build: 
      context: .
      dockerfile: Dockerfile 
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql:8.3 
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root  
      - MYSQL_DATABASE=nadinbase
      - MYSQL_USER=hesam
      - MYSQL_PASSWORD=root
      - MYSQL_TCP_PORT=3306